// frontend/components/ui/CoefWindow.jsx

function CoefWindow(props){
    
    return(
        <li className="flex justify-between">
            <span className={`font-medium mx-2 text-lg ${props.Active ? "text-red-500" : "text-black"} `}>{props.Title}</span>
            <span className={`font-extrabold mx-2 text-lg ${props.Active ? "text-red-500" : "text-black"} `}>x{props.Coef}</span>
        </li>
    );
}

export default CoefWindow;

// vue-frontend/src/components/ui/CoefWindow.vue
<template>
  <li class="flex justify-between">
    <span :class="['font-medium mx-2 text-lg', active ? 'text-red-500' : 'text-black']">
      {{ title }}
    </span>
    <span :class="['font-extrabold mx-2 text-lg', active ? 'text-red-500' : 'text-black']">
      x{{ coef }}
    </span>
  </li>
</template>

<script setup>
defineProps({
  title: String,
  coef: [Number, String],
  active: Boolean
});
</script>
